#!/usr/bin/env bash
# Install Daily Scheduler as a proper desktop app (not a .sh) so the panel/taskbar
# can pin it: a no-extension command on PATH + an XDG .desktop entry whose
# StartupWMClass / app-id match what Qt advertises (see app.DESKTOP_FILE_ID).
#
# Usage (from the repo root):
#   ./install-launcher.sh
#   ./install-launcher.sh --uninstall
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
NAME="daily-scheduler"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
APP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/256x256/apps"
WRAPPER="$BIN_DIR/$NAME"
DESKTOP="$APP_DIR/$NAME.desktop"
ICON_PNG="$ICON_DIR/$NAME.png"

uninstall() {
  rm -f "$WRAPPER" "$DESKTOP" "$ICON_PNG"
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$APP_DIR" 2>/dev/null || true
  fi
  if command -v kbuildsycoca6 >/dev/null 2>&1; then
    kbuildsycoca6 2>/dev/null || true
  elif command -v kbuildsycoca5 >/dev/null 2>&1; then
    kbuildsycoca5 2>/dev/null || true
  fi
  echo "Removed launcher: $WRAPPER"
  echo "Removed desktop entry: $DESKTOP"
  echo "Removed icon: $ICON_PNG"
  exit 0
}

if [[ "${1:-}" == "--uninstall" || "${1:-}" == "uninstall" ]]; then
  uninstall
fi

# Ensure a usable venv (same policy as run.sh).
if [[ ! -x "$ROOT/.venv/bin/python" ]]; then
  echo "Creating virtual environment (.venv)…"
  python3 -m venv "$ROOT/.venv"
  "$ROOT/.venv/bin/python" -m pip install -q -r "$ROOT/requirements.txt"
fi

mkdir -p "$BIN_DIR" "$APP_DIR" "$ICON_DIR"

# Icon (app's own ◈ design) — best-effort; desktop entry still works without it.
if [[ -x "$ROOT/.venv/bin/python" && -f "$ROOT/packaging/render_icon.py" ]]; then
  echo "Rendering icon…"
  QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-offscreen}" \
    "$ROOT/.venv/bin/python" "$ROOT/packaging/render_icon.py" "$ICON_PNG" 256 \
    || echo "  (icon render failed — continuing without a custom icon)"
fi

# Wrapper command with NO .sh suffix. Desktop shells and the taskbar pin this as
# the application executable. exec -a makes argv[0] match the desktop id.
cat > "$WRAPPER" << EOF
#!/usr/bin/env bash
# Daily Scheduler launcher — generated by install-launcher.sh (do not hand-edit).
set -euo pipefail
ROOT="$ROOT"
cd "\$ROOT" || exit 1
PY="\$ROOT/.venv/bin/python"
if [[ ! -x "\$PY" ]]; then
  echo "Daily Scheduler: missing \$PY — re-run install-launcher.sh or ./run.sh" >&2
  exit 1
fi
# argv0 = daily-scheduler so process lists / some WMs see an app name, not "python".
exec -a $NAME "\$PY" "\$ROOT/app.py" "\$@"
EOF
chmod +x "$WRAPPER"

# Quote-safe Exec= for the desktop entry.
q() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

cat > "$DESKTOP" << EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Daily Scheduler
GenericName=Daily Planner
Comment=Daily planner with a local AI assistant
Exec="$(q "$WRAPPER")"
Path=$(q "$ROOT")
Icon=$NAME
Terminal=false
Categories=Office;Calendar;Qt;
StartupNotify=true
StartupWMClass=$NAME
# Same id as app.DESKTOP_FILE_ID / QGuiApplication.setDesktopFileName
X-KDE-StartupNotify=true
Keywords=planner;schedule;calendar;ollama;
EOF

# Desktop databases / KDE menu cache
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$APP_DIR" 2>/dev/null || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" 2>/dev/null || true
fi
if command -v kbuildsycoca6 >/dev/null 2>&1; then
  kbuildsycoca6 2>/dev/null || true
elif command -v kbuildsycoca5 >/dev/null 2>&1; then
  kbuildsycoca5 2>/dev/null || true
fi

echo
echo "Installed:"
echo "  command : $WRAPPER"
echo "  desktop : $DESKTOP"
echo "  icon    : $ICON_PNG"
echo
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
  echo "Note: $BIN_DIR is not on your PATH."
  echo "  Add this to ~/.bashrc (or equivalent), then open a new terminal:"
  echo "    export PATH=\"$BIN_DIR:\$PATH\""
  echo
fi
echo "How to pin on KDE Plasma:"
echo "  1. Quit any running Daily Scheduler (tray → Quit)."
echo "  2. Launch from the app menu (or: $NAME)."
echo "  3. Right-click the taskbar icon → Pin."
echo "  Do not pin a terminal that ran ./run.sh — that pins the shell/python."
echo
echo "To remove: ./install-launcher.sh --uninstall"
